#!/bin/sh
set -e

glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
gtk-update-icon-cache -f /usr/share/icons/hicolor 2>/dev/null || true
update-desktop-database /usr/share/applications 2>/dev/null || true
